[versions]
ktx = "1.17.0"
coroutines = "1.10.2"
koin-version = "4.1.1"
serialization = "1.9.0"
junit = "4.13.2"
androidx-junit = "1.3.0"
androidx-espresso = "3.7.0"
material3 = "1.3.2"
compose-ui = "1.9.1"
activity = "1.11.0"
appcompat = "1.7.1"
material = "1.13.0"
nav-version = "2.9.4"
androidx-preference = "1.2.1"
androidx-core-role = "1.1.0"
agp-version = "8.9.2"
kotlin-version = "2.2.20"

[libraries]
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose-ui" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose-ui" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "nav-version" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "nav-version" }
androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "androidx-preference" }
androidx-core-role = { group = "androidx.core", name = "core-role", version.ref = "androidx-core-role" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose-ui" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }

kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }

koin = { group = "io.insert-koin", name = "koin-android", version.ref = "koin-version" }
koin-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin-version" }

test-junit = { group = "junit", name = "junit", version.ref = "junit" }
test-androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
test-androidx-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp-version"}
androidLibrary = { id = "com.android.library", version.ref = "agp-version"}
kotlinAndroid = {id= "org.jetbrains.kotlin.android", version.ref = "kotlin-version"}
kotlinKapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin-version"}
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-version" }
kotlinCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-version" }
